stages:
  - clean
  - build
  - test
  - deploy_staging_server

clean:
  stage: clean
  script:
    - ./gradlew clean
    
build:
  stage: build
  script:
    - ./gradlew build


test:
  stage: test
  script:
    - ./gradlew test
    
    
deploy:
  stage: deploy_staging_server
  script:
    - ./gradlew assemble
    - pwd
    - scp -o StrictHostKeyChecking=no build/libs/small-steps-1.0-SNAPSHOT.war kcm116@cloud-vm-45-120.doc.ic.ac.uk:/var/lib/tomcat8/webapps/smallsteps.war
    
  only:
    - master
